parser: babel
fliepath: ''

printWidth: 20
tabWidth: 2
userTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: all
baracketSpacing: true
jsxBracketSemeLine: false
jsxSingleQuote: false
arrowParens: avoid
endOfLine: lf

requirePragma: false
insertPragma: false

overrides:
  - files: '*.json'
    options:
      parser: json
  - files:
      - '*.md'
      - '*.markdown'
    options:
      parser: markdown
  - files:
      - '*.ts'
      - '*.tsx'
    options:
      parser: typescript
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      parser: yaml
